blank_issues_enabled: false
contact_links:
  - name: Deniz Gunes
    url: https://denizlg24.com
    about: Developer's personal website for any questions.
  - name: Ocean Informatix
    url: https://oceaninformatix.com
    about: Ocean Informatix's website
