name: "Design proposal"
description: "Propose a UI/architecture design for review"
title: "[Design] {{short_title}}"
labels: ["design", "spec"]
body:
  - type: input
    id: short_title
    attributes:
      label: "Short title"
  - type: textarea
    id: summary
    attributes:
      label: "Executive summary"
  - type: dropdown
    id: type
    attributes:
      label: "Proposal type"
      options:
        - "UI"
        - "Architecture"
        - "Data model"
  - type: textarea
    id: details
    attributes:
      label: "Full proposal"
      description: "Detailed steps, diagrams (link to images), API shapes"
  - type: input
    id: reviewers
    attributes:
      label: "Suggested reviewers"
      placeholder: "@denizlg24, @teamlead"
